baseURL = "http://example.org/"
languageCode = "tr-tr"
title = "AİDİYET"
theme = "timer-hugo"

[[menu.main]]
name    = "Anasayfa"
url     = "/"
weight  = 1
[[menu.main]]
name    = "Hakkımızda"
url     = "about"
weight  = 2
[[menu.main]]
name    = "Yayınlarımız"
url     = "yayinlarimiz"
weight  = 3
[[menu.main]]
name    = "Galeri"
url     = "galeri"
weight  = 4
[[menu.main]]
name    = "Blog"
url     = "blog"
weight  = 5
[[menu.main]]
name    = "İletişim"
url     = "iletisim"
weight  = 6

# Site Params
[params]
home = "Anasayfa"
logo = "images/TED_128.png"
dateFormat = "6 Ocak 2006"
# Meta data
description = ""
author = "Admin"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider.jpg"
heading = "MERHABA BİZ AİDİYETİZ VE BİZLER"
description = "Minik bir kıvılcımla, hevesle başlayan ve gün geçtikçe gelişen, büyüyen ekibimizle ilk sayımızı çıkarmış, sizlere sunmuş bulunuyoruz. Amacımız gün geçtikçe büyüyen ve gelişen ailemizin de katkılarıyla dergimizi sürekli kılmak ve uzun yıllar bu vizyonu sürdürebilmektir."
# button
btn     = true
btnText = "Daha Fazlası İçin"
btnURL  = "https://ted.org.tr/"

# flip text
[[params.banner.flipText]]
title   = "ÜNİVERSİTELİYİZ"
[[params.banner.flipText]]
title   = "TEB'LİYİZ"
[[params.banner.flipText]]
title   = "TED'LİYİZ"

# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT ME"
content = "Hello, I’m a UI/UX Designer & Front End Developer from Victoria, Australia. I hold a master degree of Web Design from the World University.And scrambled it to make a type specimen book. It has survived not only five centuries. <br> <br> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, adipisci voluptatum repudiandae, natus impedit repellat aut officia illum at assumenda iusto reiciendis placeat. Temporibus, vero."
image   = "images/about/about.jpg"

# Call to Action
[params.cta]
enable  = true
title   = "SO WHAT YOU THINK ?"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
btnText = "Contact with me"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Latest Works"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "#"
