baseURL = "https://aidiyet.github.io"
languageCode = "tr-tr"
title = "AİDİYET"
theme = "timer-hugo"

[[menu.main]]
name    = "Anasayfa"
url     = "/"
weight  = 1
[[menu.main]]
name    = "Hakkımızda"
url     = "service"
weight  = 2
[[menu.main]]
name    = "Yayınlarımız"
url     = "about"
weight  = 3
[[menu.main]]
name    = "Galeri"
url     = "galeri"
weight  = 4
[[menu.main]]
name    = "Blog"
url     = "blog"
weight  = 5
[[menu.main]]
name    = "İletişim"
url     = "iletisim"
weight  = 6

# Site Params
[params]
home = "Anasayfa"
logo = "images/TED_128.png"
dateFormat = "6 Ocak 2006"
# Meta data
description = ""
author = "Admin"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider.jpg"
heading = "MERHABA BİZ AİDİYETİZ VE BİZLER"
description = "Minik bir kıvılcımla, hevesle başlayan ve gün geçtikçe gelişen, büyüyen ekibimizle ilk sayımızı çıkarmış, sizlere sunmuş bulunuyoruz. Amacımız gün geçtikçe büyüyen ve gelişen ailemizin de katkılarıyla dergimizi sürekli kılmak ve uzun yıllar bu vizyonu sürdürebilmektir."
# button
btn     = true
btnText = "Daha Fazlası İçin"
btnURL  = "https://ted.org.tr/"

# flip text
[[params.banner.flipText]]
title   = "ÜNİVERSİTELİYİZ"
[[params.banner.flipText]]
title   = "TEB'LİYİZ"
[[params.banner.flipText]]
title   = "TED'LİYİZ"

# Homepage About Section
[params.about]
enable  = true
title   = "AİDİYET BÜLTEN ÇIKTI!"
content = "Vizyonumuz; TEB’li öğrenciler olarak arkadaşlarımıza, küçük kardeşlerimize, mezun büyüklerimize ve Türk Eğitim Derneği ile yolları kesişmiş her yaştan insana ulaşmak ve kendimizi tanıtmak, bilgilerimizi paylaşmak... <br><br>TEB Ankara'nın bir alt kolu olan “Aidiyet Ekibi” olarak, bültenimizi sizlere sunmaktan gurur duyuyoruz! Bilgilendirici, öğretici ve eğlenceli içeriklerle ve sürprizlerle karşınıza çıkıyoruz. <br><br><a href='https://joom.ag/jABI' target='_blank'>Aidiyet Bülteni 1. sayı için tıklayınız.</a>"
image   = "images/bulten_kapak.png"

# Call to Action
[params.cta]
enable  = true
title   = "BURSLAR HAKKINDA BİLGİLENMEK İSTER MİSİNİZ ?"
content = "Türk Eğitim Derneği, üç temel misyonundan biri olan “eğitimde fırsat eşitliğine katkı sağlamak ve donanımlı nesiller yetiştirmek” amacıyla kuruluşundan itibaren maddi imkânları kısıtlı fakat başarılı öğrencilere burslar vermektedir."
btnText = "Ayrıntılı Bilgi İçin"
btnURL  = "https://ted.org.tr/burslar"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Latest Works"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
# [[params.socialIcon]]
# icon = "ion-social-facebook"
# url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "https://instagram.com/tebankara/"

# [[params.socialIcon]]
# icon = "ion-social-linkedin"
# url = "#"
